import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components2/Navbar'
import { EthereumProvider } from '@/contextProvider/smartcontractContext'
import { WalletConnection } from '@/contextProvider/walletContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
        <WalletConnection>
        <EthereumProvider>
      <NavBar />
        <main className="flex-1">
          {children}
      </main>
      </EthereumProvider>
      </WalletConnection>
        </body>
    </html>
  )
}
